update: testando sistema para falhar pipeline em caso da nota do pylint ser inferior a 7

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -62,6 +62,15 @@ jobs:
     - name: Yield situation
       run: cat pylint-report.txt
 
+    - name: Check pylint score
+      run: |
+        pylint_score=$(tail -n 2 pylint-report.txt | head -n 1 | awk '{print $7}')
+        echo "Pylint score: $pylint_score"
+        if (( $(echo "$pylint_score < 7.00" | bc -l) )); then
+          echo "Pylint score is below 7.00, failing the pipeline."
+          exit 1
+        fi
+
   delivery:
       runs-on: ubuntu-latest
       needs: build
